# Generated by Django 4.2.30 on 2026-04-14 09:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waste_catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointWasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_catalog.wastecategory')),
            ],
            options={
                'verbose_name': 'Категория пункта',
                'verbose_name_plural': 'Категории пунктов',
            },
        ),
        migrations.CreateModel(
            name='RecyclePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('schedule', models.CharField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, max_length=2000)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='points/')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('reviews_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_points', to=settings.AUTH_USER_MODEL)),
                ('waste_categories', models.ManyToManyField(related_name='points', through='points.PointWasteCategory', to='waste_catalog.wastecategory')),
            ],
            options={
                'verbose_name': 'Пункт приёма',
                'verbose_name_plural': 'Пункты приёма',
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_per_kg', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('comment', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waste_catalog.wastecategory')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='points.recyclepoint')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='waste_catalog.wastesubcategory')),
            ],
            options={
                'verbose_name': 'Цена приёма',
                'verbose_name_plural': 'Цены приёма',
            },
        ),
        migrations.AddField(
            model_name='pointwastecategory',
            name='point',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='points.recyclepoint'),
        ),
        migrations.AddIndex(
            model_name='recyclepoint',
            index=models.Index(fields=['-average_rating'], name='points_recy_average_6c341a_idx'),
        ),
        migrations.AddIndex(
            model_name='recyclepoint',
            index=models.Index(fields=['is_active'], name='points_recy_is_acti_5a3ddf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pointwastecategory',
            unique_together={('point', 'category')},
        ),
    ]
