# Generated by Django 4.2.30 on 2026-04-14 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WasteCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('preparation_instructions', models.TextField(blank=True)),
                ('what_accepted', models.TextField(blank=True)),
                ('what_not_accepted', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Категория отходов',
                'verbose_name_plural': 'Категории отходов',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WasteSubcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('marking', models.CharField(blank=True, max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='waste/')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='waste_catalog.wastecategory')),
            ],
            options={
                'verbose_name': 'Подкатегория отходов',
                'verbose_name_plural': 'Подкатегории отходов',
                'ordering': ['category', 'name'],
            },
        ),
    ]
